### ISSUE TITLE
Samengestelde taart doorsturen naar api

### ISSUE THREAD

**Issue by Tara-Tessa** [Tara-Tessa/Maak-het-Persoonlijk#3]
Als ik probeer om mijn formulier door te sturen naar strapi krijg ik deze foutmelding:
POST http://localhost:3000/undefined/totals 404 (Not Found).

Als ik process.env.STRAPI_URL console log dan krijg ik ook dat dit undefined is. 

Alvast bedankt!

https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/56c800e76a36c409f174c73e016922ddbb30273a/pages/index.js#L13-L15

**Comment by benoitboucart** [comment]
Je doet een POST naar http://localhost:3000/undefined/totals 

De URL bestaat inderdaad niet vandaar de foutmelding.
Maw dit zorgt voor een probleem: 
   `${process.env.STRAPI_URL}/totals`

Volgens de foutmelding hierboven is process.env.STRAPI_URL dus undefined. Log dit eens in je console ter verificatie. 

Heb je die process.env.STRAPI_URL juist gedefinieerd in je environment file? Heb je erna dan ook je next project opnieuw opgestart in terminal? Etc.

**Comment by Tara-Tessa** [comment]
Jaa als process.env.STRAPI_URL log in de console geeft dit undefined terug. Deze is volgens mij juist gedefinieerd in de env file en ik heb mijn project opnieuw opgestart in terminal.

**Comment by benoitboucart** [comment]
Je `handleSubmit` wordt client-side (in de browser uitgevoerd). Aangezien je env variabele geen `NEXT_PUBLIC_` prefix 
bevat zal deze client side niet gelezen kunnen worden. Publieke env variabele wilt zeggen dat die ook in de browser gelezen kan worden. Zonder die prefix zal je die enkel op de server (veiligere omgeving) kunnen lezen. Een publiekelijke env variabele mag dus nooit een wachtwoord bevatten maar wél een API URL.  

Maw: je zal de variabele NEXT_PUBLIC_STRAPI_URL moeten noemen ipv STRAPI_URL (en je project opnieuw moeten opstarten). Zie ook de laatste labolessen.

Meer info vind je hier:
`In order to expose a variable to the browser you have to prefix the variable with NEXT_PUBLIC_. For example:`
https://nextjs.org/docs/basic-features/environment-variables

Zie ook:
![image](https://user-images.githubusercontent.com/1086264/115002604-3d4a3d00-9ea5-11eb-9685-6263d24f2400.png)

**Comment by Tara-Tessa** [comment]
Als ik probeer om de decorations door te sturen naar strapi dan kan hij de e.target.decoration.value niet lezen en krijg ik undefined. Ik probeer hier om eerst te controlleren of het checked is en dan de value van deze values door te sturen. Ik krijg steeds undefined en weet niet goed hoe ik dit anders kan aanpakken of oplossen.
Alvast bedankt

https://github.com/Tara-Tessa/Maak-het-Persoonlijk/blob/8f57e67c35d3d0dac7670fe2eab26bfaa26b91eb/components/AddCake.js#L10

**Comment by benoitboucart** [comment]
Dat is nu een ander probleem.

De forEach functie geeft geen array terug maar undefined.
zet eens je forEach functie in een console.log, je zal undefined terugkrijgen.
Zie: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#return_value

Wat je nodig hebt is een `map` functie, die wél een array teruggeeft.

Maar debuggen is de boodschap. Loggen in console van wat je terugkrijgt. Loggen van het resultaat in elke loop. Loggen van de waarde die je in loop meekrijgt etc. Dit is een cruciale stap.
Probeer de array eerst juist te genereren (en sla die op in een variabele) vooraleer je je POST request uitwerkt, dat zal makkelijker zijn om te debuggen.

Succes.
